project_id = "haxswkkcpxoqyrttrkgl"

[functions.career-mentor]
verify_jwt = false

[functions.scrape-opportunities]
verify_jwt = false

[functions.generate-missions]
verify_jwt = false

[functions.generate-skill-prompts]
verify_jwt = false

[functions.generate-weekly-quests]
verify_jwt = false

[functions.enrich-careers-onet]
verify_jwt = false

[functions.enrich-careers-prospects]
verify_jwt = false

[functions.update-career-salaries]
verify_jwt = false

[functions.fill-unsplash-keywords]
verify_jwt = false

[functions.enrich-skill-explanations]
verify_jwt = false
